#数据源
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost/db_springboot?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
      initial-size: 1
      min-idle: 1
      max-active: 20
  sql:
    init:
      schema-locations: classpath:sql/db_springboot.sql
      mode: never


logging:
  level:
    root: info
    com.study: debug
